Add missing fallback (*) to ner-es mapping
The missing fallback causes this exception when using Spanish NER on 1.8.0-SNAPSHOT: 

java.lang.IllegalStateException: No fallback (*) mapping defined!
	at de.tudarmstadt.ukp.dkpro.core.api.resources.MappingProvider.getTagTypeName(MappingProvider.java:106)
	at de.tudarmstadt.ukp.dkpro.core.api.resources.MappingProvider.getTagType(MappingProvider.java:72)